  version: 0.2
  phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Updating apt-get
      - apt-get update
      - echo Installing Maven
      - apt-get install -y maven
  pre_build:
    commands:
      - echo Pre-build phase started on date
      - mvn --version
  build:
    commands:
      - echo Build started on date
      - echo Building the Maven project...
      - mvn clean install
  post_build:
    commands:
      - echo Post-build phase started on date
      - echo test comment
  artifacts:
   files:
   - target/*.war
  discard-paths: yes
